### ISSUE TITLE
Running a script from another script

### ISSUE THREAD

**Issue by LiorBitton** [LiorBitton/startup-scripts#1]
The issue is in startup.py , I am trying to make it run two scripts that are supposed to run all the time(while True / Listeners) but startup.py stops once it calls the first scripts because it is waiting for the exit code from the executed script.

**Comment by dragid10** [comment]
I'd like to take this on!

**Comment by LiorBitton** [comment]
Thank you very much @dragid10 , You can start working on it and I will assign you.
